name: Publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-dev[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/jupytext

    permissions:
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Build package
        run: |
          python -m pip install wheel build
          # Ensure that we build jupyterlab extension and distribute it with wheel
          HATCH_BUILD_HOOKS_ENABLE=true python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
