name: test-pip
run-name: Run tests using Pip

on:
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pip:
    continue-on-error: ${{ matrix.experimental || false }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8, 3.9, "3.10", "3.11"]
        markdown-it-py-version: ["~=2.0"]
        kernel: [true]
        include:
          - python-version: "3.12-dev"
            experimental: true
          - python-version: "3.13-dev"
            experimental: true
          - python-version: 3.9
            markdown-it-py-version: ""
          - python-version: 3.9
            markdown-it-py-version: "~=3.0"
          - python-version: "3.11"
            markdown-it-py-version: "~=4.0"
            experimental: true
          - python-version: 3.9
            kernel: false
          - python-version: 3.9
            quarto: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install markdown-it-py
        if: ${{ matrix.markdown-it-py-version }}
        run: python -m pip install markdown-it-py${{ matrix.markdown-it-py-version }}

      - name: Install from source (required for the pre-commit tests)
        run: python -m pip install '.[test-cov]'

      - name: Install a Jupyter Kernel
        if: ${{ matrix.kernel }}
        run: python -m ipykernel install --name python_kernel --user

      - name: Install Quarto
        if: ${{ matrix.quarto }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          # download the latest release
          gh release download --repo quarto-dev/quarto-cli --pattern 'quarto-*-linux-amd64.deb'
          # install it
          sudo apt install ./*.deb

      - name: Test with pytest
        run: pytest --cov=jupytext --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
